name: power_perceiver
channels:
  - pytorch
  - conda-forge
  - pvlib
dependencies:
  - python>=3.9

  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - xarray
  - h5netcdf
  - pathy
  - hydra-core
  - fsspec
  - gcsfs # required to download testing data
  - pvlib # required to predict PV power using clearsky irradiance
  - cartopy

  # Machine learning
  - pytorch::pytorch # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.
  - pytorch-lightning
  - einops
  - wandb
  - scikit-learn # used for TSNE

  # Development tools
  - pytest
  - pytest-cov
  - flake8
  - black
  - pre-commit
  - pydocstyle
  - isort
