name: power_perceiver
channels:
  - pytorch
  - fastchan
  - conda-forge
  - pvlib
dependencies:
  # We need Python 3.10 for `@dataclass(kw_only=True)`. If 3.10 isn't convenient,
  # then it should be fairly simple to use the `attrs` project, which supports
  # `kw_only` on Python < 3.10.
  - python>=3.10
  - pip

  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - xarray
  - h5netcdf
  - pathy
  - hydra-core
  - fsspec
  - gcsfs # required to download testing data
  - pvlib # required to predict PV power using clearsky irradiance
  - cartopy # for plotting geospatial imagery
  - pyresample # for reprojecting the topographical data
  - bottleneck # for xarray.ffill
  - rioxarray # for loading topographical data
  - pyproj # for topographical data & coordinate transforms
  - zarr # For training the U-Net directly from satellite data
  - dask # For training the U-Net directly from satellite data

  # Machine learning
  - pytorch::pytorch # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.
  # - cpuonly # Enable when installing on a platform without a GPU.
  - fastai
  - pytorch-lightning
  - einops
  - wandb
  - scikit-learn # used for TSNE

  # Development tools
  - pytest
  - pytest-cov
  - flake8
  - black
  - pre-commit
  - pydocstyle
  - isort
  - mypy

  - pip:
      - pytorch-msssim
      # - pytorch-forecasting  # Used for Ranger optimizer (not currently used)
