name: Python package

on:
  push:
  schedule:
    - cron: "0 12 * * 1"
jobs:
  call-run-python-tests:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      # 0 means don't use pytest-xdist
      pytest_numcpus: "0"
      # pytest-cov looks at this folder
      pytest_cov_dir: "power_perceiver"
